### PR TITLE
Use `ipykernel` Patched for Python 3

### PR DESCRIPTION
**Pull request by jamesmcclain**
Still Needs:
   - [x] https://github.com/ipython/ipykernel/pull/243 (included logic to patch rather than wait for PR)

### CODE REVIEW

**Review by jpolchlo — APPROVED** [review]

**Comment by jamesmcclain** [comment]
I realized that I may need to add more to this.  There are probably some dependencies in here that will need to be changed.  Can I get back at you later?

**Comment by jamesmcclain** [comment]
@jpolchlo Would you mind taking another look at this?  I would like to merge this as-is and perhaps make a follow up PR if/when ipython/ipykernel#243 is merged

**Review by jpolchlo — APPROVED** [review]
Looks good.  My only concern with the contents has to do with our tendency to thrash between install scripts and just loading up the Dockerfile, depending on who last worked on the project.  We should collectively decide to do it one way or the other and just stick with it.  Not entirely germane to a PR review, but a comment for the future.

**Comment by jamesmcclain** [comment]
Yeah, I think we grew all of these scripts back when the build was more complicated (toree and friends).  There is very little going on now, so it seems better to just put the entire build in one easy-to-see place.

**Pull request merged**
